{% set name = "backports.shutil_which" %}
{% set version = "3.5.2" %}
{% set sha256 = "fe39f567cbe4fad89e8ac4dbeb23f87ef80f7fe8e829669d0221ecdb0437c133" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - backports
  run:
    - python
    - backports

test:
  imports:
    - backports
    - backports.shutil_which

about:
  home: https://github.com/minrk/backports.shutil_which
  license: PSF2 & MIT
  license_file: LICENSE
  summary: 'Backport of shutil.which from Python 3.3'

extra:
  recipe-maintainers:
    - kain88-de
    - minrk
