travis:
  secure:
    BINSTAR_TOKEN: ljEt7m4TRb6SSsA4FqQNPDRe3UvM/MYk+DwivzBRI8OVEmX5rLi6FVc55+n8BV9JRlwK56l50RoUkEkaPZspjLTdIEMqS2k5qSv9PrPAt207VXzirIqsYqatN90/JdpgZ1MA1axIiI6da+6nUZUgCvq25yuk9cgn0MiSkGFkKyPGVD8+NTH5afZhEK6Pn3N1JcuxjhKNV9kTrsQsTTnJucdEBnM0tC68RECt776RnJHwYyYPty1PdszwCXTMKmLXsdf/gt5HpziTfDVQZzrg12W/T6eUQRMFvjzIo4W+g8LFTc4b6p5bHEhDgwAwxWxrIj71pH+akCE/O+xzmAcsdUmLYWTQQSunzNYfh6k6ndyilOi/p4AtaSKiTMT5dD5gdjEKFt2gsTFSuSZR6/lcl77LpiLUGo5qKu422vBqhKyMyAlqOhBIGY1D2FyCPfk3RNrAuRAG8GO7NoyFhPf5h7kfGCTq1Kve9ByRnDyY6DArWbh74xF91Y5VD1MZbciWoAWeNfGgb9i9W4g+AAlCZ84aAhc5ui6hnDDhHWTa8DZdSD3tn2RSxPy7CRp4wFGCoK4itZ1w2kBXWr5H2bX2FV4XJdKjwh5CHrkeB5UwRL/DLarA/bUNDrJUaieFqa5uM8m2ONnHUlWnpBpJMcZ6c9kFqWJPRGfWqPUWHvfJ9b0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
