travis:
  secure:
    BINSTAR_TOKEN: UUxlwIFOyxxJkYZuAaxZXlP8SVQkT+PdsZoYyB2QVY4cMjtaNwg4uunkGTvufiCVnzEtlx39nQDSHTboPXQEi7s0AjkgT/zQXbr0HWVq3uzeVlFB6fceSMANZK13rO6T3nHbCWdZ3/cVSfMYKutbFnvsCckaGd1dXgfhdepE8b4hDGNG+8n9bPTW7MX4rNZCWRBa2ssBVqVIP2mLydCnPTC5BvRqsX/MFInXDQxn9S9HxNteo1KLpFgako7d6ILj8i4AHcA/qyxmP7e9rsC0tOqyBDreAYhSp99sl1f+TaNSLwMVz0WGb3mMJXkLv7gK0STwf8u4YMN4slD93c7C/SjLijUkfafkBjF256sA/wQ5zfhHv7f3TlV3N4wTb4c5W0WLyKsGfsGPRCeBTSjSkkbR7d46tTyTXHSl3NfiPvFhPz0cUbFUgL320ke07PloUzJTm+jjg3RKJzNU3ApAzFxljgzJmSUDE5SNjb33agq71ZOeV/TnoAC1qAViV7DVC9lOx4AclW1usTZkfrbQkEShr2iLSQRqDjH/rahAZaRs/ukmaZSHrmNnhYBs3cPueI6z3f/P1FlwXmmL3huZl+3tgmbWfzuT2p7zHQV4z+T3+p/WzLR6O72+rizmFx0C78zDiUS8QTHvzZWHBNJKk0XJVqKZntk3MiSPngs0iVQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
